# Generated by Django 3.0.5 on 2023-05-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20230516_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='ToDoItem',
        ),
        migrations.AddField(
            model_name='todotask',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Category'),
        ),
    ]
