# Generated by Django 3.0.5 on 2023-05-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20230516_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='title',
            new_name='task',
        ),
    ]
