# Generated by Django 3.0.5 on 2023-05-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20230516_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='todolist.Category'),
        ),
    ]
