# Generated by Django 3.0.5 on 2023-05-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20230517_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
