# Generated by Django 3.0.5 on 2023-05-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20230517_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todotask',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
