# Generated by Django 3.0.5 on 2023-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_todotask_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='deadline_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='deadline_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
