# Generated by Django 3.0.5 on 2023-05-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_auto_20230519_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='deadline_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='deadline_time',
            field=models.TimeField(),
        ),
    ]
